In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.tsa.stattools import adfuller

import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

from lab.fvg_study import FairValueGapDetector
from lab.high_low_study import HighLowDetector
sns.set_theme(style="whitegrid")

In [2]:
df = pd.read_csv('../db/raw_parque/January_MNQ.csv')
fvg = FairValueGapDetector(candles = df, threshold = 50, time_frame = '30min')
fvg.run_detector()

,high,high_ts,low,low_ts,type,spread
0,25713.50,2026-01-08 15:00:00,25774.00,2026-01-08 14:00:00,bearish,242.0
1,25646.00,2026-01-08 19:30:00,25667.00,2026-01-08 20:30:00,bullish,84.0
2,25654.00,2026-01-09 01:30:00,25673.25,2026-01-09 02:30:00,bullish,77.0
3,25696.50,2026-01-09 09:00:00,25716.75,2026-01-09 10:00:00,bullish,81.0
4,25923.50,2026-01-09 18:00:00,25948.00,2026-01-09 19:00:00,bullish,98.0
...,...,...,...,...,...,...
67,26130.25,2026-01-29 01:30:00,26147.50,2026-01-29 02:30:00,bullish,69.0
68,26200.00,2026-01-29 03:30:00,26214.50,2026-01-29 04:30:00,bullish,58.0
69,25868.50,2026-01-29 15:00:00,26131.75,2026-01-29 14:00:00,bearish,1053.0
70,25753.50,2026-01-29 15:30:00,25858.25,2026-01-29 14:30:00,bearish,419.0
71,25881.50,2026-01-29 20:00:00,25948.00,2026-01-29 21:00:00,bullish,266.0

In [3]:
fvg.candles

,window_start,ticker,symbol,contract_month,contract_year,transactions,open,high,low,close,session_end_date,settlement_price,dollar_volume,volume,timeframe
0,2026-01-08 11:30:00,MNQH6,MNQ,H,2026.0,2931,25775.25,25785.00,25764.50,25770.75,2026-01-08,NaN,161999129,6285,30min
1,2026-01-08 12:00:00,MNQH6,MNQ,H,2026.0,6262,25770.50,25777.75,25746.50,25774.50,2026-01-08,NaN,344122343,13358,30min
2,2026-01-08 12:30:00,MNQH6,MNQ,H,2026.0,4643,25774.00,25777.25,25753.75,25767.50,2026-01-08,NaN,240696406,9342,30min
3,2026-01-08 13:00:00,MNQH6,MNQ,H,2026.0,8386,25767.25,25810.50,25757.00,25804.00,2026-01-08,NaN,424851591,16474,30min
4,2026-01-08 13:30:00,MNQH6,MNQ,H,2026.0,11785,25803.50,25818.75,25786.00,25799.25,2026-01-08,NaN,589585363,22854,30min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,2026-01-29 22:00:00,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,30min
1030,2026-01-29 22:30:00,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,30min
1031,2026-01-29 23:00:00,MNQH6,MNQ,H,2026.0,17523,25994.50,26012.25,25884.00,25941.50,2026-01-30,NaN,761639835,29353,30min
1032,2026-01-29 23:30:00,MNQH6,MNQ,H,2026.0,11614,25942.00,26019.00,25939.75,25972.00,2026-01-30,NaN,503704269,19384,30min
1033,2026-01-30 00:00:00,MNQH6,MNQ,H,2026.0,561,25971.50,25981.00,25968.00,25969.75,2026-01-30,NaN,22805635,878,30min

In [4]:
fvg.visualize()

In [5]:
high_low = HighLowDetector(candles=df, time_frame='5min')

In [6]:
len(df)

21143

In [ ]:
high_low.run_detector()
high_low.visualize()

(            window_start ticker symbol contract_month  contract_year  \
 3    2026-01-08 11:50:00  MNQH6    MNQ              H         2026.0
 4    2026-01-08 11:55:00  MNQH6    MNQ              H         2026.0
 5    2026-01-08 12:00:00  MNQH6    MNQ              H         2026.0
 10   2026-01-08 12:25:00  MNQH6    MNQ              H         2026.0
 11   2026-01-08 12:30:00  MNQH6    MNQ              H         2026.0
 ...                  ...    ...    ...            ...            ...
 6185 2026-01-29 23:00:00  MNQH6    MNQ              H         2026.0
 6186 2026-01-29 23:05:00  MNQH6    MNQ              H         2026.0
 6192 2026-01-29 23:35:00  MNQH6    MNQ              H         2026.0
 6194 2026-01-29 23:45:00  MNQH6    MNQ              H         2026.0
 6195 2026-01-29 23:50:00  MNQH6    MNQ              H         2026.0

       transactions      open      high       low     close session_end_date  \
 3              585  25777.00  25785.00  25774.00  25780.00       2026-01-08
 4              591  25780.00  25781.25  25767.75  25770.75       2026-01-08
 5             1859  25770.50  25774.75  25746.50  25752.25       2026-01-08
 10             776  25773.25  25777.75  25767.75  25774.50       2026-01-08
 11            1046  25774.00  25774.75  25757.50  25761.25       2026-01-08
 ...            ...       ...       ...       ...       ...              ...
 6185          2952  25994.50  26012.25  25950.00  25952.75       2026-01-30
 6186          2633  25952.50  25998.25  25950.75  25958.25       2026-01-30
 6192          2030  25995.00  26019.00  25991.75  26008.25       2026-01-30
 6194          2148  26004.25  26011.75  25971.00  25991.25       2026-01-30
 6195          1044  25990.50  25994.00  25973.00  25978.75       2026-01-30

       settlement_price  dollar_volume  volume timeframe
 3                  NaN       31787901    1233      5min
 4                  NaN       32450366    1259      5min
 5                  NaN      100591462    3905      5min
 10                 NaN       38762965    1504      5min
 11                 NaN       52123371    2023      5min
 ...                ...            ...     ...       ...
 6185               NaN      129672961    4991      5min
 6186               NaN      126133147    4857      5min
 6192               NaN       89148640    3428      5min
 6194               NaN       95719685    3683      5min
 6195               NaN       44636806    1718      5min

 [3704 rows x 15 columns],
             window_start ticker symbol contract_month  contract_year  \
 0    2026-01-08 11:35:00  MNQH6    MNQ              H         2026.0
 1    2026-01-08 11:45:00  MNQH6    MNQ              H         2026.0
 2    2026-01-08 12:00:00  MNQH6    MNQ              H         2026.0
 3    2026-01-08 12:05:00  MNQH6    MNQ              H         2026.0
 4    2026-01-08 12:10:00  MNQH6    MNQ              H         2026.0
 ...                  ...    ...    ...            ...            ...
 3763 2026-01-29 22:55:00    NaN    NaN            NaN            NaN
 3764 2026-01-29 23:10:00  MNQH6    MNQ              H         2026.0
 3765 2026-01-29 23:25:00  MNQH6    MNQ              H         2026.0
 3766 2026-01-29 23:30:00  MNQH6    MNQ              H         2026.0
 3767 2026-01-29 23:55:00  MNQH6    MNQ              H         2026.0

       transactions      open      high       low     close session_end_date  \
 0              521  25775.25  25776.25  25764.50  25771.75       2026-01-08
 1              562  25774.25  25777.75  25767.75  25777.25       2026-01-08
 2             1859  25770.50  25774.75  25746.50  25752.25       2026-01-08
 3             1295  25751.75  25761.25  25747.25  25754.75       2026-01-08
 4              768  25755.25  25763.75  25753.50  25759.50       2026-01-08
 ...            ...       ...       ...       ...       ...              ...
 3763             0       NaN       NaN       NaN       NaN              NaN
 3764          3450  25958.75  25961.00  25901.25  25907.00       2026-01-30
 3765          4330  25957.75  25983.50  25884.00  25941.50       2026-01-30
 3766          3750  25942.00  26002.25  25939.75  25994.75       2026-01-30
 3767          1495  25978.25  25980.75  25957.00  25972.00       2026-01-30

       settlement_price  dollar_volume  volume timeframe
 0                  NaN       31157221    1209      5min
 1                  NaN       30385966    1179      5min
 2                  NaN      100591462    3905      5min
 3                  NaN       71673105    2783      5min
 4                  NaN       44975299    1746      5min
 ...                ...            ...     ...       ...
 3763               NaN              0       0      5min
 3764               NaN      144575433    5576      5min
 3765               NaN      180754731    6967      5min
 3766               NaN      159893471    6156      5min
 3767               NaN       65442823    2520      5min

 [3768 rows x 15 columns])